'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var USER_REQUEST = exports.USER_REQUEST = 'USER_REQUEST';
var USER_REQUEST_SUCCESS = exports.USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
var USER_REQUEST_FAILURE = exports.USER_REQUEST_FAILURE = 'USER_REQUEST_FAILURE';
var USER_LOGOUT = exports.USER_LOGOUT = 'USER_LOGOUT';
var USER_SUBMISSION_ACCESS = exports.USER_SUBMISSION_ACCESS = 'USER_SUBMISSION_ACCESS';
var USER_FORM_ACCESS = exports.USER_FORM_ACCESS = 'USER_FORM_ACCESS';