'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SUBMISSION_REQUEST = exports.SUBMISSION_REQUEST = 'SUBMISSION_REQUEST';
var SUBMISSION_SAVE = exports.SUBMISSION_SAVE = 'SUBMISSION_SAVE';
var SUBMISSION_SUCCESS = exports.SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS';
var SUBMISSION_FAILURE = exports.SUBMISSION_FAILURE = 'SUBMISSION_FAILURE';
var SUBMISSIONS_REQUEST = exports.SUBMISSIONS_REQUEST = 'SUBMISSIONS_REQUEST';
var SUBMISSIONS_SUCCESS = exports.SUBMISSIONS_SUCCESS = 'SUBMISSIONS_SUCCESS';
var SUBMISSIONS_FAILURE = exports.SUBMISSIONS_FAILURE = 'SUBMISSIONS_FAILURE';
var SUBMISSION_RESET = exports.SUBMISSION_RESET = 'SUBMISSION_RESET';