import {FormioComponents} from '../../factories';

// import address from './address';
import Button from './button/Button';
// import checkbox from './checkbox';
import Columns from './columns/Columns';
// import container from './container';
// import Content from './content/Content';
// import currency from './currency';
// import custom from './custom';
// import datagrid from './datagrid';
// import editgrid from './editgrid';
import Datetime from './datetime/Datetime';
import Day from './day/Day';
// import email from './email';
import Fieldset from './fieldset/Fieldset';
// import file from './file';
// import hidden from './hidden';
import HtmlElement from './htmlelement/HtmlElement';
// import number from './number';
import Panel from './panel/Panel';
// import password from './password';
// import phoneNumber from './phoneNumber';
import Radio from './radio/Radio';
// import resource from './resource';
// import survey from './survey';
// import select from './select';
// import selectboxes from './selectboxes';
import Signature from './signature/Signature';
// import table from './table';
// import textarea from './textarea';
import TextField from './textfield/TextField';
// import time from './time';
// import well from './well';

// FormioComponents.register('address', address);
FormioComponents.register('button', Button);
// FormioComponents.register('checkbox', checkbox);
FormioComponents.register('columns', Columns);
// FormioComponents.register('container', container);
// FormioComponents.register('content', Content);
// FormioComponents.register('currency', currency);
// FormioComponents.register('custom', custom);
// FormioComponents.register('datagrid', datagrid);
// FormioComponents.register('editgrid', editgrid);
FormioComponents.register('datetime', Datetime);
FormioComponents.register('day', Day);
// FormioComponents.register('email', email);
FormioComponents.register('fieldset', Fieldset);
// FormioComponents.register('file', file);
// FormioComponents.register('hidden', hidden);
FormioComponents.register('htmlelement', HtmlElement);
// FormioComponents.register('number', number);
FormioComponents.register('panel', Panel);
// FormioComponents.register('password', password);
// FormioComponents.register('phoneNumber', phoneNumber);
FormioComponents.register('radio', Radio);
// FormioComponents.register('resource', resource);
// FormioComponents.register('survey', survey);
// FormioComponents.register('select', select);
// FormioComponents.register('selectboxes', selectboxes);
FormioComponents.register('signature', Signature);
// FormioComponents.register('table', table);
// FormioComponents.register('textarea', textarea);
FormioComponents.register('textfield', TextField);
// FormioComponents.register('time', time);
// FormioComponents.register('well', well);
